# Generated by Django 4.2.18 on 2025-03-04 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attendees",
            fields=[
                (
                    "Attendees_ID",
                    models.IntegerField(
                        max_length=10, primary_key=True, serialize=False
                    ),
                ),
                ("Employee_Name", models.CharField(max_length=100)),
                ("Designation", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Meetings",
            fields=[
                (
                    "Meeting_ID",
                    models.IntegerField(
                        max_length=10, primary_key=True, serialize=False
                    ),
                ),
                ("Meeting_Date", models.DateField()),
                ("Meeting_Location", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Points",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Points_Discussed", models.CharField(max_length=1000)),
                (
                    "Attendees_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="appo.attendees"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="attendees",
            name="Meeting_ID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="appo.meetings"
            ),
        ),
    ]
