# Generated by Django 4.2.18 on 2025-03-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendees",
            name="Attendees_ID",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="meetings",
            name="Meeting_ID",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
