# Generated by Django 4.2.18 on 2025-03-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appo", "0002_alter_attendees_attendees_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendees",
            name="Email",
            field=models.EmailField(default="esha@gamil.com", max_length=254),
        ),
    ]
