# Generated by Django 4.2.18 on 2025-03-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appo", "0003_attendees_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="points",
            name="Point_Type",
            field=models.CharField(default="support", max_length=100),
        ),
    ]
