# Generated by Django 4.2.18 on 2025-03-04 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "Country_Code",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "State_Name",
                    models.CharField(
                        max_length=1000, primary_key=True, serialize=False
                    ),
                ),
                (
                    "Country_Code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app1.country"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                ("Pincode", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "State_Name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app1.state"
                    ),
                ),
            ],
        ),
    ]
