# Generated by Django 4.2.18 on 2025-03-18 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="dept",
            fields=[
                ("deptno", models.IntegerField(primary_key=True, serialize=False)),
                ("dname", models.CharField(max_length=100)),
                ("loc", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="emp",
            fields=[
                ("empno", models.IntegerField(primary_key=True, serialize=False)),
                ("ename", models.CharField(max_length=100)),
                ("job", models.CharField(max_length=100)),
                ("sal", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "comm",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("hiredate", models.DateField(auto_now=True)),
                (
                    "deptno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.dept"
                    ),
                ),
                (
                    "mgr",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.emp",
                    ),
                ),
            ],
        ),
    ]
